//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CoEOSSISO.rc
//
#define IDS_PROJNAME                    100
#define IDR_EOSSISO                     102
#define IDD_EOSSSUMMARY_PAGE            113
#define IDD_EOSSMODPARAMS_PAGE          114
#define IDD_EOSSDATASTATUS_PAGE         115
#define IDD_BINARYEOSSDATASTATUS_PAGE   116
#define IDD_GPSDATASTATUS_PAGE          117
#define IDD_VACOSSDATASTATUS_PAGE       118
#define IDD_PROPPAGE_LEGEND             119
#define IDI_CLOCK                       136
#define IDI_FLAG                        137
#define IDI_BELL                        138
#define IDI_FACE                        139
#define IDI_FLOPPY                      140
#define IDI_SKULL                       141
#define IDI_BOMB                        142
#define IDB_BMP_ALL                     200
#define IDC_RICHEDIT1                   201
#define IDC_CURSOR_HAND                 202
#define IDD_DIALOG1                     203
#define IDC_STATIC_CHECKER              204
#define IDD_DIALOG_ADD                  205
#define IDC_BUTTON_REMOVEDATA           206
#define IDC_BUTTON_UPDATEDISPLAY        207
#define IDC_BUTTON_RUNNOW               208
#define IDC_STATIC_MESSAGE2             209
#define IDC_BUTTON_RUNNOW2              209
#define IDC_TREE1                       211
#define IDC_ADD_ID                      212
#define IDC_ADD_DUP_TXT                 213
#define IDC_STATUS_TXT                  214
#define IDC_BUTTON_EDIT                 222
#define IDC_BUTTON_DELETE               224
#define IDC_BUTTON_ADD                  225
#define IDC_LIST1                       228
#define IDC_BUTTON_MOVEUP               230
#define IDC_BUTTON_MOVEDOWN             231
#define IDC_EOSSDATA_TAB                2299
#define IDC_EOSSDATA_FIRST              2300
#define IDC_EOSSDATA_MSG                2300
#define IDC_EOSSDATA_LAST               2300
#define IDC_LEGEND_GREEN                2600
#define IDC_LEGEND_YELLOW               2601
#define IDC_LEGEND_RED                  2602
#define IDC_LEGEND_WHITE                2603
#define IDC_LEGEND_CYAN                 2604
#define IDC_LEGEND_GRAY                 2605
#define IDC_LEGEND_GREEN_TEXT           2606
#define IDC_LEGEND_YELLOW_TEXT          2607
#define IDC_LEGEND_RED_TEXT             2608
#define IDC_LEGEND_WHITE_TEXT           2609
#define IDC_LEGEND_CYAN_TEXT            2610
#define IDC_LEGEND_GRAY_TEXT            2611
#define IDC_LEGEND_CLOCK_TEXT           2612
#define IDC_LEGEND_FLAG_TEXT            2613
#define IDC_LEGEND_BELL_TEXT            2614
#define IDC_LEGEND_FACE_TEXT            2615
#define IDC_LEGEND_FLOPPY_TEXT          2616
#define IDC_LEGEND_SKULL_TEXT           2617
#define IDC_LEGEND_BOMB_TEXT            2618
#define IDC_LEGEND_FLAG                 2619
#define IDC_LEGEND_BELL                 2620
#define IDC_LEGEND_FACE                 2621
#define IDC_LEGEND_FLOPPY               2622
#define IDC_EOSSSUMMARY_FIRST           4601
#define IDC_EOSSSUMMARY_COMMAND1        4601
#define IDC_EOSSSUMMARY_COMMAND2        4602
#define IDC_EOSSSUMMARY_COMMAND3        4603
#define IDC_EOSSSUMMARY_COMMAND4        4604
#define IDC_EOSSSUMMARY_COMMAND5        4605
#define IDC_EOSSSUMMARY_COMMAND6        4606
#define IDC_EOSSSUMMARY_COMMAND7        4607
#define IDC_EOSSSUMMARY_COMMAND8        4608
#define IDC_EOSSSUMMARY_COMMAND9        4609
#define IDC_EOSSSUMMARY_COMMAND10       4610
#define IDC_EOSSSUMMARY_COMMAND11       4611
#define IDC_EOSSSUMMARY_LAST            4611
#define IDC_GOTO_EOSS_DATASTAT          4629
#define IDC_EOSSMODPARAMS_FIRST         4700
#define IDC_EOSSMODPARAMS_PORT          4700
#define IDC_EOSSMODPARAMS_NODE_SPIN     4701
#define IDC_EOSSMODPARAMS_NODE          4702
#define IDC_EOSSMODPARAMS_MAXPAUSE      4703
#define IDC_EOSSMODPARAMS_MAXPAUSE_SPIN 4704
#define IDC_EOSSMODPARAMS_APPLY         4705
#define IDC_EOSSMODPARAMS_MAINBATLOW    4706
#define IDC_EOSSMODPARAMS_MAINBATLOW_SPIN 4707
#define IDC_EOSSMODPARAMS_EMERBATLOW    4708
#define IDC_EOSSMODPARAMS_EMERBATLOW_SPIN 4709
#define IDC_EOSSMODPARAMS_MAINBATCRIT   4710
#define IDC_EOSSMODPARAMS_MAINBATCRIT_SPIN 4711
#define IDC_EOSSMODPARAMS_RESET         4712
#define IDC_EOSSMODPARAMS_EMERBATCRIT   4713
#define IDC_EOSSMODPARAMS_EMERBATCRIT_SPIN 4714
#define IDC_EOSSMODPARAMS_SAVELOC       4715
#define IDC_EOSSMODPARAMS_BROWSE        4716
#define IDC_EOSSMODPARAMS_LOGFILTER     4717
#define IDC_EOSSMODPARAMS_DEFAULT       4718
#define IDC_EOSSMODPARAMS_FILEID        4719
#define IDC_EOSSMODPARAMS_FILEID_SPIN   4720
#define IDC_EOSSMODPARAMS_STATICTEXT    4721
#define IDC_EOSSMODPARAMS_PW            4722
#define IDC_EOSSMODPARAMS_COMBOWHEN     4723
#define IDC_EOSSMODPARAMS_DOM           4724
#define IDC_EOSSMODPARAMS_DOW           4725
#define IDC_EOSSMODPARAMS_HOURS         4726
#define IDC_EOSSMODPARAMS_MINUTES       4727
#define IDC_EOSSMODPARAMS_ACCOUNT       4728
#define IDC_EOSSMODPARAMS_PRESENCE_CHECK 4729
#define IDC_EOSSMODPARAMS_FULL_ESTIMATE 4730
#define IDC_EOSSMODPARAMS_PRESENCE_ESTIMATE 4731
#define IDC_EOSSMODPARAMS_OFFSETHOURS   4732
#define IDC_EOSSMODPARAMS_TIMEERROR     4733
#define IDC_EOSSMODPARAMS_TIMEERROR_SPIN 4734
#define IDC_EOSSMODPARAMS_INTERVAL      4735
#define IDC_EOSSMODPARAMS_READER_LOG    4736
#define IDC_EOSSMODPARAMS_GATHER_SCHED  4737
#define IDC_EOSSMODPARAMS_LAST          4737
#define IDC_CHECK_ALLOWAUTODATE         4749
#define IDC_CHECK_BINARY                4750
#define IDC_STATIC_ADVERT               5328
#define IDC_STATIC_DEBUG                5331
#define IDC_BBM_VALUE                   20200
#define IDC_BADYEAR_VALUE               20201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         227
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
