// ALLOWTRIGGERHOLDOFF.h 

// See StdAfx.h for inclusion of this file

#ifndef ALLOWTRIGGERHOLDOFF_H
#define ALLOWTRIGGERHOLDOFF_H

#undef ALLOWTRIGGERHOLDOFF
//#define ALLOWTRIGGERHOLDOFF

#endif //ALLOWTRIGGERHOLDOFF_H