// CSO_definitions.h 

#ifndef CSO_DEFINITIONS_H
#define CSO_DEFINITIONS_H

#define ISZSTRING (-1)

#define WATCHDOG		"WATCHDOG"
#define WATCHDOGPORT	"WATCHDOGPORT"

#define LOCALLONGBREAK	"LOCALLONGBREAK"
#define LONGBREAK		"LONGBREAK"
#define LONGBREAKSET	"LONGBREAKSET"
#define LONGBREAKCLR	"LONGBREAKCLR"

#define COMSTATUSDE		"COMSTATUSDE"
#define COMSTATUSLE		"COMSTATUSLE"

#define COM_LOOP_BACK_MODE_MESSAGE
//#undef COM_LOOP_BACK_MODE_MESSAGE

#endif //CSO_DEFINITIONS_H