// ini_definitions.h

#ifndef INI_DEFINITIONS_H
#define INI_DEFINITIONS_H

#define AUTORESTARTCOUNT	"AUTORESTARTCOUNT"
#define BAUDRATE			"BaudRate"
#define BEATNIK				"BEAT"
#define BUTTONWIDTH			"ButtonWidth"
#define BUTTONFLAGS			"BUTTONFLAGS"
#define BUTTONFLAGSIZE		"ButtonFlagSize"
#define BUTTONHEIGHT		"ButtonHeight"
#define BUTTONSWIDE			"ButtonsWide"  //number of columns of buttons
#define COMMFAIL			"COMMFAIL"
#define COMMUNICATIONS		"Communications"
#define CONFIGURATION		"Configuration"
#define LAST_VALIDATION		"Last_Validation"
#define DATABITS			"DataBits"
#define DAYSBEFOREDELFILES	"DaysBeforeDelFiles"
#define DEFAULTCOPYPATH		"DefaultCopyPath"
#define DIALOGCLOSE			"DialogClose"
#define DOINGNETWORK		"ACTIVE"       //<<QA>> maybe we should rename for clarity
#define DO_DUMP				"DO_DUMP"
#define DOSHORTNAME			"DOSHORTNAME"
#define FACILITYNAME		"FacilityName"
#define FASTSTARTUP			"FastStartup"
#define FILE_ID				"FILE_ID"
#define FLAGCOMM			"FLAGCOMM"
#define FLAGTIME			"FLAGTIME"
#define FLAGOTHR			"FLAGOTHR"
#define HIDEWATCH			"HideWatch"
#define HIDEWINDOWS			"HideWindows"
#define INSTRUMENTS			"Instruments"
#define IPDATE				"IPDate"
#define LAST_X				"LAST_X"
#define LAST_Y				"LAST_Y"
#define LOG_MII				"LOG_MII"
#define LOGARCHIVEACT		"LogArchiveAct"
#define LONGNAMEFORM		"LONGNAMEFORM"
#define MAXPAUSE			"MAXPAUSE"
#define MAXPERCENTDISKUSE	"MaxPercentDiskUse"
#define MAX_REP					"MAX_REP"
#define MINUTESTOCHECKARCHIVE	"MinutesToCheckArchive"
#define MODE					"Mode"
#define NETWORK					"NETWORK"
#define NODE					"NODE"
#define NORMALSHUTDOWN			"NormalShutdown"
#define PARITY					"Parity"
#define PORT					"Port"
#define SAVE_LOC				"SAVE_LOC"
#define SLOW_RESET				"SLOW_RESET"
#define SLOWSTART				"SlowStart"
#define SOH_APPEND				"SOH_APPEND"
#define SOH_BAD					"SOH_BAD"
#define SOH_BADTOGOOD			"SOH_BADTOGOOD"
#define SOH_GOOD				"SOH_GOOD"
#define SOH_LIMITED_EXT			"SOH_LIMITED_EXT"
#define SOH_PATH				"SOH_PATH"
#define SOH_PATH_EXT			"SOH_PATH_EXT"
#define SOH_TIME_EXT			"SOH_TIME_EXT"
#define SOH_TIME_EXT_LAST		"SOH_TIME_EXT_LAST"
#define SOH_DAILY				"SOH_DAILY"
#define SOH_DAILYAT				"SOH_DAILYAT"
#define STOPBITS				"StopBits"
#define SUPERUSERS				"SuperUsers"
#define USERS					"Users"

#endif //INI_DEFINITIONS.H